# Generated by Django 6.1 on 2026-08-21 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.CharField(max_length=255, verbose_name="ID do objeto")),
                (
                    "task_id",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="ID da tarefa"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(blank=True, max_length=255, verbose_name="nome da tarefa"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("STARTED", "Em execução"),
                            ("RETRY", "Repetindo"),
                            ("SUCCESS", "Concluída"),
                            ("FAILURE", "Falhou"),
                            ("REVOKED", "Revogada"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criada em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizada em")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="tipo de conteúdo",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="celery_task_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="iniciada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de tarefa",
                "verbose_name_plural": "registros de tarefas",
                "ordering": ["-created_at"],
                "permissions": [("view_task_trace", "Can view full task error trace")],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="django_cele_content_3d5758_idx"
                    )
                ],
            },
        ),
    ]
