# Generated by Django 5.2.17 on 2026-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_task_monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("STARTED", "Em execução"),
                    ("RETRY", "Repetindo"),
                    ("PROGRESS", "Em processamento"),
                    ("SUCCESS", "Concluída"),
                    ("FAILURE", "Falhou"),
                    ("REVOKED", "Revogada"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
